input_file: /app/samples/v1.mp4
triton:
  server:
    host: 'server'
    port: '8001'
    verbose: False
    shm_region_type: 'system' # 'cuda' or 'system'
  model:
    name: 'trafficcamnet'
    version: '1'
    batch_size: 1
    precision: 'FP32'
    conf_threshold: 0.5
    iou_threshold: 0.5
